export const BASKETBALLINFO = [
    {
        id:0,
        name: '6U Recreational',
        description:'Our 6U Basketball is played on a half-court with 8 foot rims to encourage. Our Recreational Basketball division is intended for those with little to no experience in the sport. No stealing or reaching in is allowed and rules are geared towards learning the offensive portion of the game. One coach is allowed on the court for each team to help the players in the younger divisions',
        rules:['Coed: Girls & Boys',
            'Ball Size: 27.5” or Junior size',
            'Court Size: Half Court',
            'Players: 4 on 4',
            'Rim Height: 8’',
            'Game: Four Quarters, Six Minutes each',
            'Coaches are Parent Volunteers',
            'NYS has a minimum 50% play rule in our recreational sports.',
            'Every kid must play at least half the game',],
        equipment:['Basketball Shoes', 'Basketball'],
        registration:['League dues for season', 'Game court fees', 'Game equipment', 'Officials', 'Liability insurance with a medical rider', 'Game jersey', 'League administration','No fundraising for the league' ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/10_b821c257-6064-4d2b-9496-7621ce76244b_2048x.png?v=1551385079'
    },
    {
        id:1,
        name: '8U Recreational',
        description:'Our 8U Recreational Basketball is intended for those with little to no experience in the sport. No stealing or reaching in is allowed and rules are geared towards learning the offensive portion of the game.',
        rules:['Coed: Girls & Boys',
            'Ball Size: 27.5” or Junior size',
            'Players: 5 on 5',
            'Court Size: Full or Cross Court',
            'Rim Height: 8’',
            'Game: Four Quarters, Eight Minutes each',
            'Coaches are Parent Volunteers',
            'No Coaches allowed on court',
            'NYS has a minimum 50% play rule in our recreational sports',
            'Every kid must play at least half the game'],
        equipment:['Basketball Shoes', 'Basketball'],
        registration:['League dues for season', 'Game court fees', 'Game equipment', 'Officials', 'Liability insurance with a medical rider', 'Game jersey', 'League administration','No fundraising for the league' ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/14_ec43b621-3b94-4b86-944f-618db54d72be_2048x.png?v=1551208906'
    },
    {
        id:2,
        name: '11U Recreational',
        description:'Our 11U Recreational Basketball is intended for those with a little experience in the sport. ',
        rules:['Coed: Girls & Boys',
            'Ball Size: 28.5” or Junior size',
            'Players: 5 on 5',
            'Court Size: Full or Cross Court',
            'Rim Height: 10’',
            'Game: Four Quarters, Eight Minutes each',
            'Coaches are Parent Volunteers',
            'No Coaches allowed on court',
            'NYS has a minimum 50% play rule in our recreational sports',
            'Every kid must play at least half the game'],
        equipment:['Basketball Shoes', 'Basketball'],
        registration:['League dues for season', 'Game court fees', 'Game equipment', 'Officials', 'Liability insurance with a medical rider', 'Game jersey', 'League administration','No fundraising for the league' ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/46_2048x.png?v=1551208957'
    },
    {
        id:3,
        name: '8U Elite',
        description:'Our 8U Elite Basketball Program is for those players with experience in the sport. It is fully competitive, including scores, standings, playoffs, and championships. The division includes a stricter rule set and referee guidelines. Standings are updated weekly online.',
        rules:['Coed: Girls & Boys',
            'Ball Size: 27.5',
            'Court Size: Full or Cross Court',
            'Rim Height: 10’ -Regulation',
            'Game: Four Quarters, Eight Minutes each. Clock stops in last 2 minutes of the 4th quarter',
            'Coaches are Parent Volunteers',
            'Playing time is not guaranteed in our competitive divisions',
            'Playing time is not guaranteed in our Elite Sports and is at the sole discretion of the Head Coach'],
        equipment:['Basketball Shoes', 'Basketball'],
        registration:['League dues for season', 'Game court fees', 'Game equipment', 'Officials', 'Liability insurance with a medical rider', 'Game jersey', 'League administration','No fundraising for the league' ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/25_794f4651-b661-4ef8-ac66-fce28b0fb83e_2048x.png?v=1551208925'
    },
    {
        id:4,
        name: '10U Elite',
        description:'Our 10U Elite Basketball Program is for those players with experience in the sport. It is fully competitive, including scores, standings, playoffs, and championships. The division includes a stricter rule set and referee guidelines. Standings are updated weekly online.',
        rules:['Coed: Girls & Boys',
            'Ball Size: Regulation',
            'Court Size: Full or Cross Court',
            'Rim Height: 10’ -Regulation',
            'Game: Four Quarters, Eight Minutes each. Clock stops in last 2 minutes of the 4th quarter',
            'Coaches are Parent Volunteers',
            'Playing time is not guaranteed in our competitive divisions',
            'Playing time is not guaranteed in our Elite Sports and is at the sole discretion of the Head Coach'],
        equipment:['Basketball Shoes', 'Basketball'],
        registration:['League dues for season', 'Game court fees', 'Game equipment', 'Officials', 'Liability insurance with a medical rider', 'Game jersey', 'League administration','No fundraising for the league' ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/45_220x170_crop_center.png?v=1551384992'
    },
    {
        id:5,
        name: '12U Elite',
        description:'Our 12U Elite Basketball Program is for those players with experience in the sport. It is fully competitive, including scores, standings, playoffs, and championships. The division includes a stricter rule set and referee guidelines. Standings are updated weekly online.',
        rules:['Coed: Girls & Boys',
            'Ball Size: Regulation',
            'Court Size: Full or Cross Court',
            'Rim Height: 10’ -Regulation',
            'Game: Four Quarters, Eight Minutes each. Clock stops in last 2 minutes of the 4th quarter',
            'Coaches are Parent Volunteers',
            'Playing time is not guaranteed in our competitive divisions',
            'Playing time is not guaranteed in our Elite Sports and is at the sole discretion of the Head Coach'],
        equipment:['Basketball Shoes', 'Basketball'],
        registration:['League dues for season', 'Game court fees', 'Game equipment', 'Officials', 'Liability insurance with a medical rider', 'Game jersey', 'League administration','No fundraising for the league' ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/25_794f4651-b661-4ef8-ac66-fce28b0fb83e_2048x.png?v=1551208925'
    },
    {
        id:6,
        name: '15U Elite',
        description:'Our 15U Elite Basketball Program is for those players with experience in the sport. It is fully competitive, including scores, standings, playoffs, and championships. The division includes a stricter rule set and referee guidelines. Standings are updated weekly online.',
        rules:['Coed: Girls & Boys',
            'Ball Size: Regulation',
            'Court Size: Full or Cross Court',
            'Rim Height: 10’ -Regulation',
            'Game: Four Quarters, Eight Minutes each. Clock stops in last 2 minutes of the 4th quarter',
            'Coaches are Parent Volunteers',
            'Playing time is not guaranteed in our competitive divisions',
            'Playing time is not guaranteed in our Elite Sports and is at the sole discretion of the Head Coach'],
        equipment:['Basketball Shoes', 'Basketball'],
        registration:['League dues for season', 'Game court fees', 'Game equipment', 'Officials', 'Liability insurance with a medical rider', 'Game jersey', 'League administration','No fundraising for the league' ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/25_794f4651-b661-4ef8-ac66-fce28b0fb83e_2048x.png?v=1551208925'
    },
]