export const FLAGFOOTBALL = [
    {
        id:0,
        name:'Recreational Flag Football',
        description:`Designed for beginner's to the game of flag football.  There are no scores kept, and no playoffs or championships.  Games are played for fun without any of the pressures of winning or losing.  NYS utilizes the NFL Flag Football 5 v 5 rules that maximize participation.`,
        groups:['6U: Ages 4-6 years old',
            '8U: Ages 6-8 years old',            
            '11U: Ages 8-11 years old'],
        rules:['Coed: Boys & Girls',
            'Ball:  6U - Mini Ball.  8U & 11U -  PeeWee (NFL Blue)',
            'Players on the field: 5 vs. 5',
            'Field Size: 30 yards x 70 yards w/ 2 10 yard end zones',
            'Game: 2 halves, 20 minutes each',
            'Coaches are Parent Volunteers',
            'NYS has a minimum 50% play rule in our recreational sports',
            'Every kid must play at least half the game'],
        equipment:['Rubber Cleats',' Mouthpiece'],
        register:'None',
        provided:['Flags','Football'],
        registration:[`Game jersey top`, `League dues for season`, `Game fields`, `Officials`, `Liability insurance with a medical rider`, `League administration` ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/DSC_5826-EDITED_2048x.png?v=1551209068'
    },
    {
        id:1,
        name:'Elite NFL Flag Football',
        description:`Designed for those with a little experience in the game of flag football.  Players wear reversible the NFL Replica Game Jerseys.  NFL Flag Football includes standings, scores, and a full playoff system with awards.  Teams have a chance to compete in Regional and National NFL Flag Football Tournaments.`,
        groups:[`8U: Ages 6-8 years old`,
            `10U: Ages 8-10 years old`,
            `12U: Ages 10-12 years old`,
            `14U: Ages 12-14 years old`,           
            `16U Girls:  Girls Ages 12-16`],
        rules:[`Coed: Boys & Girls`,
            `Ball:  8U & 10U -  PeeWee (NFL Blue), 12U & 14U  - Junior (NFL Brown)`,
            `Players on the field: 5 vs. 5`,
            `Field Size: 30 yards X 70 yards w/ 2 10 yard end zones`,
            `Game: 2 halves, 20 minutes each`,
            `Coaches are Parent Volunteers`,
            `Playing time is not guaranteed in our Elite Sports and is at the sole discretion of the Head Coach`],
        equipment:['Rubber Cleats',' Mouthpiece'],
        register:` Photo/Scan of Birth Certificate or Passport, and closeup headshot without a hat or glasses on showing the child's entire face and hair. You will upload this on your account when you register online or you can email to info@nysnevada.com`,
        provided:['Flags','Football'],
        registration:[`Game jersey top`, `League dues for season`, `Game fields`, `Officials`, `Liability insurance with a medical rider`, `League administration` ],
        image:'https://cdn.shopify.com/s/files/1/0012/3895/8164/files/DSC_6151-EDITED_6da2d177-4c1d-415a-abed-32519005d420_2048x.png?v=1551209084'
    },
]