export const UNIFORM = [
    {
        id:0,
        name:'Soccer',
        size:['Select...','xxsmall','xsmall','Small','Medium','Large','X-Large','XX-Large'],
        price:'$19.95',
        image:'/assets/images/soccer_uniform.png',
    },
    {
        id:1,
        name:'Baseball',
        size:['Select...','xxsmall','xsmall','Small','Medium','Large','X-Large','XX-Large'],
        price:'$19.95',
        image:'/assets/images/baseball_uniform.png',
    },
    {
        id:2,
        name:'Flag Football',
        size:['Select...','xxsmall','xsmall','Small','Medium','Large','X-Large','XX-Large'],
        price:'$19.95',
        image:'/assets/images/flag_football_uniform.png',
    },
    {
        id:3,
        name:'Basketball',
        size:['Select...','xxsmall','xsmall','Small','Medium','Large','X-Large','XX-Large'],
        price:'$19.95',
        image:'/assets/images/basketball_uniform.png',
    },
    {
        id:4,
        name:'Volleyball',
        size:['Select...','xxsmall','xsmall','Small','Medium','Large','X-Large','XX-Large'],
        price:'$19.95',
        image:'/assets/images/volleyball_uniform.png',
    },
]